# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QGraphicsView, QGraphicsScene, QGraphicsEllipseItem
from PyQt5.QtGui import QPainter, QColor, QPen, QBrush, QImage 
from PyQt5.QtCore import pyqtSlot, Qt, QPointF
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class MainWindowSlots():
    def exit_button():
        exit()

    def findDot(points,pos_x, pos_y):
        for i in range(len(points)):
            if((pos_x > (points[i].pos().x() - 12)) and (pos_x < (points[i].pos().x() + 12))):
                if((pos_y > (points[i].pos().y() - 12)) and (pos_y < (points[i].pos().y() + 12))):
                    return i

    def openMessage():
        tutorial = QMessageBox()
        tutorial.setWindowTitle("Instruction")
        tutorial.setText("Добро пожаловать в наше приложение!\n\n В приложении вы можете переключаться между 3 режимами:\n 1. Режим перемещения точек - Left Ctrl\n 2. Режим добавления точек - Left Ctrl\n 3. Режим удаления точек - Left Shift\n\n Информация о текущем режиме отображена в строке состояния.\n Для начала рисования необходимо добавить минимум 3 точки, и передвинуть одну из них.")
        tutorial.setIcon(QMessageBox.Information)
        tutorial.setStandardButtons(QMessageBox.Ok)
        tutorial.exec()


class MovingObject(QGraphicsEllipseItem):
    def __init__(self, x, y, r):
        super().__init__(0, 0, r, r)
        self.setPos(x, y)
        self.setBrush(Qt.red)
        self.setAcceptHoverEvents(True)
        self.redact = False

    def hoverEnterEvent(self, event):
        if(self.redact):
            app.instance().setOverrideCursor(Qt.OpenHandCursor)

    def hoverLeaveEvent(self, event):
        app.instance().restoreOverrideCursor()

    def mousePressEvent(self, event):
        pass


    def mouseMoveEvent(self, event):        
        super().mouseMoveEvent(event)
        if(self.redact):
            orig_cursor_position = event.lastScenePos()
            updated_cursor_position = event.scenePos()

            orig_position = self.scenePos()

            updated_cursor_x = updated_cursor_position.x() - orig_cursor_position.x() + orig_position.x()
            updated_cursor_y = updated_cursor_position.y() - orig_cursor_position.y() + orig_position.y()
            self.setPos(QPointF(updated_cursor_x, updated_cursor_y))

    def mouseReleaseEvent(self, event):
        super().mouseReleaseEvent(event) 
        

class RunObject(QGraphicsEllipseItem):
    def __init__(self, x, y, r, parent1, parent2):
        super().__init__(0, 0, r, r)
        self.setPos(x, y)
        self.setBrush(Qt.blue)
        self.parent1 = parent1
        self.parent2 = parent2

    



class Test(QGraphicsView):
    def __init__(self, label):
        super().__init__()
        self.setFocusPolicy(Qt.StrongFocus)
        self.initUI()
        self.points = []
        self.isDraw = False
        self.drawedPath = None
        self.label = label        
        self.radius = 5
        self.lines_onScene = []
        self.lines = []
        self.inner_lines = []
        self.dots = []
        self.inner_dots = []
        self.step = 1;
        self.max_step = 1000
        self.par_step = 0.001
        self.rev = 1
        self.bezier_path = []
        self.changed = True

    def initUI(self):     
        self.scene = QGraphicsScene()
        self.setScene(self.scene)       
        self.setSceneRect(110, 100, 450, 350) 
        self.pressing = False  
        self.mouse_posX = None
        self.mouse_posY = None
        self.redact = False
        self.delete = False
        self.obj = None
        self.update()
    
        
    def keyPressEvent(self, QKeyEvent):
        super().keyPressEvent(QKeyEvent)
        if(QKeyEvent.key() == 16777249):  # "Left Ctrl" Button - needs for Redactor Mode On/Off
            if(self.redact):
                self.redact = False
                if(len(self.points) > 0):
                    for i in range(len(self.points)):
                        self.points[i].redact = True
                
                self.label.setText("Режим: перемещение точек")
                self.delete = False
                self.update()
            else:
                self.redact = True
                if(len(self.points) > 0):
                    for i in range(len(self.points)):
                        self.points[i].redact = False
                
                self.label.setText("Режим: добавление точек")                
                self.delete = False
                self.update()
        
        if(QKeyEvent.key() == 16777248):
            self.redact = False
            self.delete = True
            self.label.setText("Режим: удаления точек")


    def mousePressEvent(self, QMouseEvent):
        super().mousePressEvent(QMouseEvent)
        self.mouse_posX = QMouseEvent.pos().x() + 80
        self.mouse_posY = QMouseEvent.pos().y() + 70
        self.pressing = True
        self.update()
                
        if not self.mouse_posX or not self.pressing:
            return

        if(self.redact and not self.delete):            
            self.obj = MovingObject(self.mouse_posX, self.mouse_posY, 12)
            self.scene.addItem(self.obj)
            self.points.append(self.obj)
            self.changed = True

        if(self.delete):        
            i = MainWindowSlots.findDot(self.points, self.mouse_posX, self.mouse_posY)
            if i != None:
                self.scene.removeItem(self.points[i])
                self.points.pop(i)
            if(self.drawedPath != None and len(self.points) < 3):
                self.scene.removeItem(self.drawedPath)
                self.update() 
            if(self.lines_onScene != None and len(self.points) == 1):
                self.scene.removeItem(self.lines_onScene[0])
                self.update()                
            self.changed = True
        
    def del_bez(self):
        if(self.bezier_path != None):
            for i in range(len(self.bezier_path) - 1):
                self.scene.removeItem(self.bezier_path[i])


    def draw_bez(self):
        self.bezier_points = self.get_bezier_points()
        if(self.bezier_points != None):
            for i in range(len(self.bezier_points) - 1):
                self.bezier_path.append(self.scene.addLine(QLineF(self.bezier_points[i].x() + 6, self.bezier_points[i].y() + 6,
                         self.bezier_points[i + 1].x()+ 6, self.bezier_points[i + 1].y() + 6), QPen(QtCore.Qt.blue)))
            
        self.update()
    
    def mouseReleaseEvent(self, QMouseEvent):
        super().mouseReleaseEvent(QMouseEvent)   
        self.pressing = False
        self.update()
        self.changed = True
        
    def get_bezier_points(self):
        par = 0.0
        bezier_points = []
        while par < 1:
            buffer_points = self.points
            while len(buffer_points) != 1:
                next_points = []
                for i in range(0, len(buffer_points) - 1):                    
                    point = [buffer_points[i].x() + par * (buffer_points[i + 1].x() - buffer_points[i].x()),
                             buffer_points[i].y() + par * (buffer_points[i + 1].y() - buffer_points[i].y())]
                    next_points.append(QPoint(int(point[0]),int(point[1])))
                buffer_points = next_points
            bezier_points.append(buffer_points[0])
            par = par + self.par_step
        return bezier_points

    def paintEvent(self, event):
        super().paintEvent(event)
        if( len(self.lines_onScene) == len(self.points) == 1):
            if(self.changed):                
                self.del_bez()
                self.changed = False
            for j in range(len(self.lines_onScene)):
                self.scene.removeItem(self.lines_onScene[j])
            for j in range(len(self.dots)):
                self.scene.removeItem(self.dots[j])
                
            for j in range(len(self.inner_lines)):
                self.scene.removeItem(self.inner_lines[j])
            self.lines = []
            self.lines_onScene = []
            self.dots = []                
            self.inner_dots = []                
        
        if(len(self.points) == 2):
            if(self.changed):                
                self.del_bez()
                self.changed = False
            if((self.isDraw) and (self.lines_onScene != None)):
                for j in range(len(self.lines_onScene)):
                    self.scene.removeItem(self.lines_onScene[j])
                for j in range(len(self.dots)):
                    self.scene.removeItem(self.dots[j])
                
                for j in range(len(self.inner_lines)):
                    self.scene.removeItem(self.inner_lines[j])
                
                self.lines = []
                self.lines_onScene = []
                self.dots = []                
                self.inner_dots = []
            self.isDraw = True
            self.pen = QPen(QColor(0, 0, 0))
            self.pen.setWidth(2)
            self.lines.append(QLineF(self.points[0].x() + 6,self.points[0].y() + 6, self.points[1].x() + 6,self.points[1].y() + 6))
            if(len(self.lines_onScene) > 0):
                self.lines_onScene[0] = self.scene.addLine(self.lines[0],self.pen)
            else:
                self.lines_onScene.append(self.scene.addLine(self.lines[len(self.lines)-1], self.pen))
            
            step = (self.lines[0].p2() - self.lines[0].p1())/self.max_step
            if(self.rev > 0):
                    self.dot = self.scene.addEllipse(self.lines[0].x1() + self.step * step.x() * self.rev - 6,self.lines[0].y1() + self.step * step.y() * self.rev - 6, 12, 12, self.pen,QBrush(QtCore.Qt.green, style = QtCore.Qt.SolidPattern))
            else:
                self.dot = self.scene.addEllipse(self.lines[0].x2() + self.step * step.x() * self.rev - 6,self.lines[0].y2() + self.step * step.y() * self.rev - 6, 12, 12, self.pen,QBrush(QtCore.Qt.green, style = QtCore.Qt.SolidPattern))
            self.dots.append(self.dot)
        elif((len(self.points) > 2) ): #and not (self.redact)
            if(self.changed):                
                self.del_bez()
                self.draw_bez()
                self.changed = False
            if(self.isDraw):
                for j in range(len(self.lines_onScene)):
                    self.scene.removeItem(self.lines_onScene[j])
                for j in range(len(self.dots)):
                    self.scene.removeItem(self.dots[j])
                
                for j in range(len(self.inner_lines)):
                    self.scene.removeItem(self.inner_lines[j])

                self.lines = []
                self.lines_onScene = []
                self.dots = []                
                self.inner_dots = []
            for i in range(len(self.points) - 1):
                self.lines.append(QLineF(self.points[i].x() + 6,self.points[i].y() + 6, self.points[i + 1].x() + 6,self.points[i + 1].y() + 6))
                self.lines_onScene.append(self.scene.addLine(self.lines[i],self.pen))
                step = (self.lines[i].p2() - self.lines[i].p1())/self.max_step
                if(self.rev > 0):
                    self.inner_dots.append(QPointF(self.lines[i].x1() + self.step * step.x() * self.rev - 6,self.lines[i].y1() + self.step * step.y() * self.rev - 6))
                    self.dot = self.scene.addEllipse(self.inner_dots[i].x(),self.inner_dots[i].y(), 12, 12, self.pen,QBrush(QtCore.Qt.yellow, style = QtCore.Qt.SolidPattern))
                else:
                    self.inner_dots.append(QPointF(self.lines[i].x2() + self.step * step.x() * self.rev - 6,self.lines[i].y2() + self.step * step.y() * self.rev - 6))
                    self.dot = self.scene.addEllipse(self.inner_dots[i].x(), self.inner_dots[i].y(), 12, 12, self.pen,QBrush(QtCore.Qt.yellow, style = QtCore.Qt.SolidPattern))
                self.dots.append(self.dot)
            
            self.inner_lines = []
            ind = len(self.inner_dots)
            dist = 0
            if(len(self.inner_dots) > 1):
                i = len(self.lines_onScene)
                while(i > 1):                    
                    k = 0
                    for j in range(i - 1):
                        self.lines.append(QLineF(self.inner_dots[j + dist].x() + 6, self.inner_dots[j + dist].y() + 6, self.inner_dots[j + 1 + dist].x() + 6, self.inner_dots[j + 1 + dist].y() + 6))
                        self.inner_lines.append(self.scene.addLine(self.lines[len(self.lines) - 1], self.pen))                        
                        step = (self.lines[len(self.lines) - 1].p2() - self.lines[len(self.lines) - 1].p1())/self.max_step
                        if(self.rev > 0):
                            self.inner_dots.append(QPointF(self.lines[len(self.lines) - 1].x1() + self.step * step.x() * self.rev - 6,self.lines[len(self.lines) - 1].y1() + self.step * step.y() * self.rev - 6))
                            self.dot = self.scene.addEllipse(self.inner_dots[len(self.inner_dots) - 1].x(),self.inner_dots[len(self.inner_dots) - 1].y(), 12, 12, self.pen,QBrush(QtCore.Qt.yellow, style = QtCore.Qt.SolidPattern))
                        else:
                            self.inner_dots.append(QPointF(self.lines[len(self.lines) - 1].x2() + self.step * step.x() * self.rev - 6,self.lines[len(self.lines) - 1].y2() + self.step * step.y() * self.rev - 6))
                            self.dot = self.scene.addEllipse(self.inner_dots[len(self.inner_dots) - 1].x(),self.inner_dots[len(self.inner_dots) - 1].y(), 12, 12, self.pen,QBrush(QtCore.Qt.yellow, style = QtCore.Qt.SolidPattern))
                        self.dots.append(self.dot)
                        k += 1
                    i -= 1
                    dist = len(self.inner_dots) - k
                                     
            self.dots[len(self.dots)-1].setBrush(QBrush(QtCore.Qt.green, style = QtCore.Qt.SolidPattern))
           
            self.isDraw = True
            self.update()


        if(self.step == self.max_step):
            self.step = 1
            self.rev = self.rev * (-1)
        else:
            self.step += 1
        self.update()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 70, 200, 20))
        self.label.setFont(QtGui.QFont("Times", 9, QtGui.QFont.Bold))
        self.label.setObjectName("label")
        self.label.setText("Режим: перемещение точек")
        
        self.test = Test(self.label)

        self.horizontalLayoutWidget_1 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_1.setGeometry(QtCore.QRect(110, 100, 500, 400))
        self.horizontalLayoutWidget_1.setObjectName("horizontalLayoutWidget_1")


        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_1)
        self.horizontalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayout_1.addWidget(self.test)


        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(630, 450, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")


        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")


        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_2.clicked.connect(MainWindowSlots.exit_button)


        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(630, 70, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")


        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")


        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(MainWindowSlots.openMessage)


        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.pushButton.setText(_translate("MainWindow", "Tutorial"))

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
